name: "HCL AppScan CodeSweep Publish"
on:
  pull_request
    types: [closed]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish issues to ASoC
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2
        with:
          asoc_key: ${{ secrets.ASOC_KEY }}
          asoc_secret: ${{ secrets.ASOC_SECRET }}
          publish_on_merge: true
          application_id: 65e179ff-7e6a-4b84-994b-8a92af6390e0
    env: 
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
